#!/usr/bin/perl
# 
# Copyright © 2015-2020 by Vincent Slyngstad
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS LISTED ABOVE BE LIABLE
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# 
# Except as contained in this notice, the names of the authors above
# shall not be used in advertising or otherwise to promote the sale, use
# or other dealings in this Software without prior written authorization
# from those authors.

# "Triple-packed" packed floppies just pack 2 words 
# into 3 bytes.  Here, we just unpack the 3 bytes 
# into two words.

foreach $f (@ARGV) {
  open(INPUT, $f) || die "$f: $!";
  binmode(INPUT);
  $of = $f; $of =~ s/[.]rx01//; $of =~ s/[.]3p//; $of .= ".dsk";
  open(OUTPUT, ">$of") || die "$of: $!";
  binmode(OUTPUT);
  while (read(INPUT, $buf, 3*128) == 3*128) {
    @buf = unpack("C*", $buf);
    while (@buf) {
      $b1 = shift @buf;
      $b2 = shift @buf;
      $b3 = shift @buf;
      # The bit ordering is fugly:
      # abcdefgh ijklmnop qrstuvwx 
      # -> abcdijklmnop efghqrstuvwx
      $word1 = ($b2 << 16) + ($b1 << 8) + $b3;
      $word2 = $word1 & 07777;
      $word1 = $word1 >> 12;
      $word1 = (($word1&017)<<8) + ($word1 >> 4);
      print OUTPUT pack("SS", $word1, $word2);
    }
  }
}
